"""added field status

Revision ID: 30d3a9984be7
Revises: e9ad7655f0e4
Create Date: 2024-11-22 19:35:32.594664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d3a9984be7'
down_revision: Union[str, None] = 'e9ad7655f0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('status', sa.Enum('WORKING', 'OFF', 'SICK', 'VACATION', name='daystatus'), nullable=False))
    op.alter_column('salary', 'base_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('salary', 'overtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('salary', 'earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salary', 'earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('salary', 'overtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('salary', 'base_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('salary', 'status')
    # ### end Alembic commands ###
