"""upgrade table remind

Revision ID: a7cac01b5f1e
Revises: 3f12a13dcbb6
Create Date: 2024-11-17 12:18:35.286091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cac01b5f1e'
down_revision: Union[str, None] = '3f12a13dcbb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
