"""delete table remind

Revision ID: 7d95bd600f1f
Revises: 31293e437313
Create Date: 2024-11-30 15:08:51.117213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d95bd600f1f'
down_revision: Union[str, None] = '31293e437313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('user_chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reminds_pkey'),
    sa.UniqueConstraint('user_chat_id', name='reminds_user_chat_id_key')
    )
    # ### end Alembic commands ###
