"""create table

Revision ID: e546c6aca35a
Revises: 
Create Date: 2024-08-17 14:48:58.135178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e546c6aca35a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('base_hours', sa.Float(), nullable=False),
    sa.Column('overtime', sa.Float(), nullable=False),
    sa.Column('earned', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('overtime', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('salary')
    # ### end Alembic commands ###
