"""add field other income

Revision ID: 31293e437313
Revises: e9ad7655f0e4
Create Date: 2024-11-29 22:37:06.337154

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31293e437313'
down_revision: Union[str, None] = 'e9ad7655f0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary',
                  sa.Column('other_income', sa.Integer(), nullable=True,
                            default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'other_income')
    # ### end Alembic commands ###
