"""upgrade table remind

Revision ID: 3f12a13dcbb6
Revises: 771c4548e173
Create Date: 2024-11-17 11:58:57.038145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f12a13dcbb6'
down_revision: Union[str, None] = '771c4548e173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminds', sa.Column('user_chat_id', sa.BIGINT(), nullable=False))
    op.drop_index('ix_reminds_user_id', table_name='reminds')
    op.create_unique_constraint(None, 'reminds', ['user_chat_id'])
    op.drop_constraint('reminds_user_id_fkey', 'reminds', type_='foreignkey')
    op.drop_column('reminds', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminds', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reminds_user_id_fkey', 'reminds', 'settings', ['user_id'], ['id'])
    op.drop_constraint(None, 'reminds', type_='unique')
    op.create_index('ix_reminds_user_id', 'reminds', ['user_id'], unique=True)
    op.drop_column('reminds', 'user_chat_id')
    # ### end Alembic commands ###
